//航行中のグループ表示
export const Navigation_Group = [
    /*グループ名:{
        アイコン:text(publicファイルの写真),
        参加ユーザー:[text]
    }*/
    {
        'name':'HappyKayak',
        'icon':'/S_red_icon.png',
        'user':[
            'Yamada1234',
            'user2',
            'user3'
        ]
    },
    {
        'name':'Kayakers',
        'icon':'/O_green_icon.png',
        'user':[
            'Yamada1234',
            'user2',
            'user3',
            'user4',
            'user5',
            'user6',
        ]
    },
    {
        'name':'kayak252',
        'icon':'/A_purple_icon.png',
        'user':[
            'Yamada1234',
            'user2'
        ]
    },
    {
        'name':'tanakayak',
        'icon':'/Six_blue_icon.png',
        'user':[
            'Yamada1234',
            'user2'
        ]
    }
]

export const Friend_Diary = [
    /*フレンドネーム:{
        アイコン:text(publicファイルの写真),
        アルバム:[text(publicファイルの写真)]
    }
    */
    {
        'frendname':'Taro1234',
        'icon':'/Taro1234_icon.png',
        'album':[
            '/kayak_picture1.png',
            '/kayak_picture2.png',
            '/front_camera.png'
        ]
    },
    {
        'frendname':'Suzuki1341',
        'icon':'/Suzuki1341_icon.png',
        'album':[
            '/kayak_picture1.png',
            '/kayak_picture2.png',
            '/front_camera.png'
        ]
    },
    {
        'frendname':'090Hiroya',
        'icon':'/090Hiroya_icon.png',
        'album':[
            '/kayak_picture1.png',
            '/kayak_picture2.png',
            '/front_camera.png'
        ]
    },
]